default:
  target: dev
  outputs:
    dev:
      type: redshift
      host: "{{env_var('REDSHIFT_HOST')}}"
      user: "{{env_var('REDSHIFT_USER')}}"
      password: "{{env_var('REDSHIFT_PASSWORD')}}"
      port: 5432
      dbname: "env_var('REDSHIFT_DBNAME')"
      schema: currency
      threads: 4
      keepalives_idle: 0